export default {
  "login": "captainamiedi",
  "id": 48450805,
  "node_id": "MDQ6VXNlcjQ4NDUwODA1",
  "avatar_url": "https://avatars0.githubusercontent.com/u/48450805?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/captainamiedi",
  "html_url": "https://github.com/captainamiedi",
  "followers_url": "https://api.github.com/users/captainamiedi/followers",
  "following_url": "https://api.github.com/users/captainamiedi/following{/other_user}",
  "gists_url": "https://api.github.com/users/captainamiedi/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/captainamiedi/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/captainamiedi/subscriptions",
  "organizations_url": "https://api.github.com/users/captainamiedi/orgs",
  "repos_url": "https://api.github.com/users/captainamiedi/repos",
  "events_url": "https://api.github.com/users/captainamiedi/events{/privacy}",
  "received_events_url": "https://api.github.com/users/captainamiedi/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Bright Amidiagbe",
  "company": null,
  "blog": "",
  "location": "Lagos, Nigeria",
  "email": null,
  "hireable": null,
  "bio": "hardworking, dedicated and always willing to learn",
  "twitter_username": null,
  "public_repos": 31,
  "public_gists": 0,
  "followers": 1,
  "following": 2,
  "created_at": "2019-03-11T17:23:26Z",
  "updated_at": "2020-12-25T11:18:23Z"
};
